server:
  port: 8084

spring:
  cloud:
    stream:
      bindings:
          ClassCustomerEvent:
            group: classcustomerview

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true

