spring:
  data:
    mongodb:
      host: localhost
      database: School
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost
          zkNodes: localhost

school:
  classcustomerview:
    transaction:
      timeStoredInMinutes: 60

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
